# Estas son las plataformas de financiamiento soportadas
# Descomenta y completa las que apliquen a tu proyecto

# github: [username]
# patreon: username
# open_collective: impostor-web
# ko_fi: username
# tidelift: npm/impostor-web
# community_bridge: impostor-web
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: impostor-web
# custom: ['https://www.buymeacoffee.com/username']
